### ISSUE TITLE
zhuying - Malicious attacker can call `finalizeWithdrawsManual` to let account get less when eETH share/amount decrease

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-leveraged-vaults-judging#29]
zhuying

Medium

# Malicious attacker can call `finalizeWithdrawsManual` to let account get less when eETH share/amount decrease

## Summary
Malicious attacker can call `finalizeWithdrawsManual` to let account get less when eETH share/amount decrease.
## Vulnerability Detail
Anyone can call `finalizeWithdrawsManual` directly without access control. `finalizeWithdrawsManual` function is to get tokensClaimed from integrated protocol (ethena, etherfi, kelp) and stored in a "split" withdraw request. Account can full claim after.
Is there any chance that actual claimed amount is less than the expected claimed amount for integrated protocol?
ethena: No
etherfi: Yes
kelp: No
Let's discuss etherfi.
The `getClaimableAmount` in [WithdrawRequestNFT](https://etherscan.io/address/0xdaaac9488f9934956b55fcdaef6f9d92f8008ca7#code) contract is as follows:
```solidity
    function getClaimableAmount(uint256 tokenId) public view returns (uint256) {
        require(tokenId < nextRequestId, "Request does not exist");
        require(tokenId <= lastFinalizedRequestId, "Request is not finalized");
        require(ownerOf(tokenId) != address(0), "Already Claimed");

        IWithdrawRequestNFT.WithdrawRequest memory request = _requests[tokenId];
        require(request.isValid, "Request is not valid");

 @    // send the lesser value of the originally requested amount of eEth or the current eEth value of the shares
        uint256 amountForShares = liquidityPool.amountForShare(request.shareOfEEth);
        uint256 amountToTransfer = (request.amountOfEEth < amountForShares) ? request.amountOfEEth : amountForShares;
        uint256 fee = uint256(request.feeGwei) * 1 gwei;

        return amountToTransfer - fee;
    }
```
Code comments show it will send the lesser value of the originally requested amount of eEth or the current eEth value of the shares. 
In [etherfi doc](https://etherfi.gitbook.io/etherfi/ether.fi-whitepaper/technical-documentation#permissionless-withdrawals):
> The eETH balance of an account is computed as follows:
$BalanceOf(account)=TotalPooledEth∗\frac{Shares[account]}{TotalShares}$
-TotalPooledEth= the total amount of ETH controlled by the protocol
-Shares[account]= the account's share of eETH 
-TotalShares= the total shares of eETH
Here, TotalPooledEth= (D + P + R) as reported by the [Oracle](https://etherfi.gitbook.io/etherfi/ether.fi-whitepaper/technical-documentation#oracle):
-D= the total ETH deposits in the liquidity pool
-P= the total ETH claims on principals for the T-NFTs in the liquidity pool
-R= the total ETH claims on rewards for the T-NFTs in the liquidity pool

So if one validator get slashed, the TotalPooledEth will decrease and with the same share the account's eETH balance will decrease. If a malicious attacker notices this, he can call `finalizeWithdrawsManual` to account which don't finalize withdraw in etherfi, the account will get less than expected amount.
## Impact
Account gets less expected claimed amount in some case.
## Code Snippet
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/main/leveraged-vaults-private/contracts/vaults/staking/BaseStakingVault.sol#L267-L269
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/main/leveraged-vaults-private/contracts/vaults/common/WithdrawRequestBase.sol#L180-L198
## Tool used
manual
## Recommendation
Set a trusted role to call `finalizeWithdrawsManual`.

**Comment by psych2go** [comment]
Escalate
not duplicate of #105

**Comment by sherlock-admin3** [comment]
> Escalate
> not duplicate of #105 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate not duplicate of #105

The attacking path and method is similar in nature to #105 to diminish the intended amount after all.

**Comment by WangSecurity** [comment]
I don't think these reports are that similar, to be honest.

This report depends on the EtherFi and can only happen if there is a slashing event **and** an unclaimed withdrawal request. This leads to the user getting fewer tokens.

#105 depends on Kelp and can happen with every withdrawal request causing the complete loss of funds. Also it requires front-running while this report doesn't as I understand.

I agree it's not a duplicate of #105. But, doesn't this report explain how the protocol should work, i.e. even without the attack, if the user initiates their withdrawal before the slashing event, and finalises it after the slashing event, then they have to suffer this loss based on the EtherFi's design. If there's an access control check on `finalizeWithdrawsManual` they still wouldn't avoid this situation. Or am I wrong here?

**Comment by psych2go** [comment]
I agree with you. But eETH is a rebasing token.
https://etherscan.io/address/0x02656fe285fac5d5c756c2f03c17277df9bac65b#code
```
    /// @notice Rebase by ether.fi
    function rebase(int128 _accruedRewards) public {
        if (msg.sender != address(membershipManager)) revert IncorrectCaller();
        totalValueOutOfLp = uint128(int128(totalValueOutOfLp) + _accruedRewards);

        emit Rebase(getTotalPooledEther(), eETH.totalShares());
    }
```
Honestly if slashing event happened, the user could wait for the protocol accruing rewards to compensate loss.
In this case, access control on `finalizeWithdrawsManual` could have an effect.

**Comment by WangSecurity** [comment]
I would still say it's the design of EtherFi protocol and their eETH that the total shares decrease when there's a slashing event. Hence, I wouldn't call it a loss of funds, but a design of the protocol.

Planning to accept the escalation since it's asked for deduplication of that issue, but will invalidate it.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [psych2go](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/29/#issuecomment-2227162270): accepted
