### ISSUE TITLE
ZeroTrust - In the _splitWithdrawRequest() function, there exists an issue that causes both the from and to requestId to be 0

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-leveraged-vaults-judging#41]
ZeroTrust

High

# In the _splitWithdrawRequest() function, there exists an issue that causes both the from and to requestId to be 0

## Summary
In the _splitWithdrawRequest() function, there exists an issue that causes both the from and to requestId to be 0
## Vulnerability Detail
```javascript
 function _splitWithdrawRequest(address _from, address _to, uint256 vaultShares) internal {
 @>       WithdrawRequest storage w = VaultStorage.getAccountWithdrawRequest()[_from];
        if (w.requestId == 0) return;

        // Create a new split withdraw request
        if (!w.hasSplit) {
            SplitWithdrawRequest memory s = VaultStorage.getSplitWithdrawRequest()[w.requestId];
            // Safety check to ensure that the split withdraw request is not active, split withdraw
            // requests are never deleted. This presumes that all withdraw request ids are unique.
            require(s.finalized == false && s.totalVaultShares == 0);
            VaultStorage.getSplitWithdrawRequest()[w.requestId].totalVaultShares = w.vaultShares;
        }

        if (w.vaultShares == vaultShares) {
            // If the resulting vault shares is zero, then delete the request. The _from account's
            // withdraw request is fully transferred to _to
    @>        delete VaultStorage.getAccountWithdrawRequest()[_from];
        } else {
            // Otherwise deduct the vault shares
            w.vaultShares = w.vaultShares - vaultShares;
            w.hasSplit = true;
        }

        // Ensure that no withdraw request gets overridden, the _to account always receives their withdraw
        // request in the account withdraw slot.
        WithdrawRequest storage toWithdraw = VaultStorage.getAccountWithdrawRequest()[_to];
        require(toWithdraw.requestId == 0 || toWithdraw.requestId == w.requestId , "Existing Request");

        // Either the request gets set or it gets incremented here.
@>      toWithdraw.requestId = w.requestId;
        toWithdraw.vaultShares = toWithdraw.vaultShares + vaultShares;
        toWithdraw.hasSplit = true;
    }
```
The ‘w’ is the storage WithdrawRequest of _from. In the case of w.vaultShares equaling vaultShares, the storage WithdrawRequest of _from is deleted (meaning the storage is reset to 0). Then w.requestId becomes 0, so toWithdraw.requestId is 0.
Funds cannot be retrieved from third-party protocols, leading to a loss of funds.

## Impact
Funds cannot be retrieved from third-party protocols, leading to a loss of funds.
## Code Snippet
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/vaults/common/WithdrawRequestBase.sol#L205
## Tool used

Manual Review

## Recommendation
Please use memory cached variables.

Duplicate of #6

**Comment by 0502lian** [comment]
Escalate

Let’s take a look at some of the key lines of code.
```javascript
 function _splitWithdrawRequest(address _from, address _to, uint256 vaultShares) internal {
 @>       WithdrawRequest storage w = VaultStorage.getAccountWithdrawRequest()[_from];
        
        if (w.vaultShares == vaultShares) {
            // If the resulting vault shares is zero, then delete the request. The _from account's
            // withdraw request is fully transferred to _to
    @>        delete VaultStorage.getAccountWithdrawRequest()[_from];
        } 
        // Ensure that no withdraw request gets overridden, the _to account always receives their withdraw
        // request in the account withdraw slot.
        WithdrawRequest storage toWithdraw = VaultStorage.getAccountWithdrawRequest()[_to];
        require(toWithdraw.requestId == 0 || toWithdraw.requestId == w.requestId , "Existing Request");

        // Either the request gets set or it gets incremented here.
@>      toWithdraw.requestId = w.requestId;
        toWithdraw.vaultShares = toWithdraw.vaultShares + vaultShares;
        toWithdraw.hasSplit = true;
    }
```
Because w is in storage, after deletion, w.requestId = 0, and toWithdraw.requestId will also be 0.
Although VaultStorage.getSplitWithdrawRequest()[w.requestId].totalVaultShares = w.vaultShares; retains the correct w.vaultShares,
VaultStorage.getAccountWithdrawRequest() and VaultStorage.getSplitWithdrawRequest() are completely different data structures.

```javascript
function getAccountWithdrawRequest() internal pure returns (mapping(address => WithdrawRequest) storage store) {
        assembly { store.slot := ACCOUNT_WITHDRAW_SLOT }
    }

function getSplitWithdrawRequest() internal pure returns (mapping(uint256 => SplitWithdrawRequest) storage store) {
        assembly { store.slot := SPLIT_WITHDRAW_SLOT }
    }


```

WithdrawRequest and SplitWithdrawRequest are different data structures.
```javascript
struct WithdrawRequest {
    uint256 requestId;
    uint256 vaultShares;
    bool hasSplit;
}

struct SplitWithdrawRequest {
    uint256 totalVaultShares; // uint64
    uint256 totalWithdraw; // uint184?
    bool finalized;
}
```
Because both VaultStorage.getAccountWithdrawRequest()[_from].requestId and VaultStorage.getAccountWithdrawRequest()[_to].requestId are set to 0, VaultStorage.getSplitWithdrawRequest()[right requestId] does not have an index that can be accessed.


So funds cannot be withdraw from third-party protocols, leading to a loss of funds.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Let’s take a look at some of the key lines of code.
> ```javascript
>  function _splitWithdrawRequest(address _from, address _to, uint256 vaultShares) internal {
>  @>       WithdrawRequest storage w = VaultStorage.getAccountWithdrawRequest()[_from];
>         
>         if (w.vaultShares == vaultShares) {
>             // If the resulting vault shares is zero, then delete the request. The _from account's
>             // withdraw request is fully transferred to _to
>     @>        delete VaultStorage.getAccountWithdrawRequest()[_from];
>         } 
>         // Ensure that no withdraw request gets overridden, the _to account always receives their withdraw
>         // request in the account withdraw slot.
>         WithdrawRequest storage toWithdraw = VaultStorage.getAccountWithdrawRequest()[_to];
>         require(toWithdraw.requestId == 0 || toWithdraw.requestId == w.requestId , "Existing Request");
> 
>         // Either the request gets set or it gets incremented here.
> @>      toWithdraw.requestId = w.requestId;
>         toWithdraw.vaultShares = toWithdraw.vaultShares + vaultShares;
>         toWithdraw.hasSplit = true;
>     }
> ```
> Because w is in storage, after deletion, w.requestId = 0, and toWithdraw.requestId will also be 0.
> Although VaultStorage.getSplitWithdrawRequest()[w.requestId].totalVaultShares = w.vaultShares; retains the correct w.vaultShares,
> VaultStorage.getAccountWithdrawRequest() and VaultStorage.getSplitWithdrawRequest() are completely different data structures.
> 
> ```javascript
> function getAccountWithdrawRequest() internal pure returns (mapping(address => WithdrawRequest) storage store) {
>         assembly { store.slot := ACCOUNT_WITHDRAW_SLOT }
>     }
> 
> function getSplitWithdrawRequest() internal pure returns (mapping(uint256 => SplitWithdrawRequest) storage store) {
>         assembly { store.slot := SPLIT_WITHDRAW_SLOT }
>     }
> 
> 
> ```
> 
> WithdrawRequest and SplitWithdrawRequest are different data structures.
> ```javascript
> struct WithdrawRequest {
>     uint256 requestId;
>     uint256 vaultShares;
>     bool hasSplit;
> }
> 
> struct SplitWithdrawRequest {
>     uint256 totalVaultShares; // uint64
>     uint256 totalWithdraw; // uint184?
>     bool finalized;
> }
> ```
> Because both VaultStorage.getAccountWithdrawRequest()[_from].requestId and VaultStorage.getAccountWithdrawRequest()[_to].requestId are set to 0, VaultStorage.getSplitWithdrawRequest()[right requestId] does not have an index that can be accessed.
> 
> 
> So funds cannot be withdraw from third-party protocols, leading to a loss of funds.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by amankakar** [comment]
Same Issue as [#6](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/6).

**Comment by mystery0x** [comment]
> Escalate
> 
> Let’s take a look at some of the key lines of code.
> 
> ```js
>  function _splitWithdrawRequest(address _from, address _to, uint256 vaultShares) internal {
>  @>       WithdrawRequest storage w = VaultStorage.getAccountWithdrawRequest()[_from];
>         
>         if (w.vaultShares == vaultShares) {
>             // If the resulting vault shares is zero, then delete the request. The _from account's
>             // withdraw request is fully transferred to _to
>     @>        delete VaultStorage.getAccountWithdrawRequest()[_from];
>         } 
>         // Ensure that no withdraw request gets overridden, the _to account always receives their withdraw
>         // request in the account withdraw slot.
>         WithdrawRequest storage toWithdraw = VaultStorage.getAccountWithdrawRequest()[_to];
>         require(toWithdraw.requestId == 0 || toWithdraw.requestId == w.requestId , "Existing Request");
> 
>         // Either the request gets set or it gets incremented here.
> @>      toWithdraw.requestId = w.requestId;
>         toWithdraw.vaultShares = toWithdraw.vaultShares + vaultShares;
>         toWithdraw.hasSplit = true;
>     }
> ```
> 
> Because w is in storage, after deletion, w.requestId = 0, and toWithdraw.requestId will also be 0. Although VaultStorage.getSplitWithdrawRequest()[w.requestId].totalVaultShares = w.vaultShares; retains the correct w.vaultShares, VaultStorage.getAccountWithdrawRequest() and VaultStorage.getSplitWithdrawRequest() are completely different data structures.
> 
> ```js
> function getAccountWithdrawRequest() internal pure returns (mapping(address => WithdrawRequest) storage store) {
>         assembly { store.slot := ACCOUNT_WITHDRAW_SLOT }
>     }
> 
> function getSplitWithdrawRequest() internal pure returns (mapping(uint256 => SplitWithdrawRequest) storage store) {
>         assembly { store.slot := SPLIT_WITHDRAW_SLOT }
>     }
> ```
> 
> WithdrawRequest and SplitWithdrawRequest are different data structures.
> 
> ```js
> struct WithdrawRequest {
>     uint256 requestId;
>     uint256 vaultShares;
>     bool hasSplit;
> }
> 
> struct SplitWithdrawRequest {
>     uint256 totalVaultShares; // uint64
>     uint256 totalWithdraw; // uint184?
>     bool finalized;
> }
> ```
> 
> Because both VaultStorage.getAccountWithdrawRequest()[_from].requestId and VaultStorage.getAccountWithdrawRequest()[_to].requestId are set to 0, VaultStorage.getSplitWithdrawRequest()[right requestId] does not have an index that can be accessed.
> 
> So funds cannot be withdraw from third-party protocols, leading to a loss of funds.

Please see my comment on #6.

**Comment by WangSecurity** [comment]
Agree it's a valid issue, planning to accept the escalation and duplicate with #6.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #6

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0502lian](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/41/#issuecomment-2226692492): accepted
