### ISSUE TITLE
novaman33 - Missing oracle staleness check

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-leveraged-vaults-judging#7]
novaman33

Medium

# Missing oracle staleness check

## Summary
In _calculateBaseToQuote the updatedAt variable is still recorder but it is not used. The oracle may return stale data even if the sequencer is still up.
## Vulnerability Detail
The PendlePTOracle does check if the sequencer is up which ensures that the sequencer is operational and that the data can be trusted to a certain extent. If the sequencer is down, transactions might be delayed or not processed, leading to potential inaccuracies in the data​. 
However this check still does not guarantee that the price data is accurate.
Even if the sequencer is operational, data from oracles can still become stale due to various reasons such as network delays or issues with the data providers. 
Therefore only checking if the sequencer is up is not enough.
## Impact
Stale price could cause arbitrage opportunities for users
## Code Snippet
https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/oracles/PendlePTOracle.sol#L106
## Tool used

Manual Review

## Recommendation
A staleness check ensures that the data you are using is recent and has been updated within an acceptable time frame.

**Comment by novaman33** [comment]
Escalate, 
Even though it is checked if it is up, the other checks are also required. It can be up and return stale values.

**Comment by sherlock-admin3** [comment]
> Escalate, 
> Even though it is checked if it is up, the other checks are also required. It can be up and return stale values.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
> Escalate, Even though it is checked if it is up, the other checks are also required. It can be up and return stale values.

It has been clearly explained by the sponsors in the Discord channel that they have their own set of staleness check.

https://github.com/sherlock-audit/2024-06-leveraged-vaults/blob/14d3eaf0445c251c52c86ce88a84a3f5b9dfad94/leveraged-vaults-private/contracts/oracles/PendlePTOracle.sol#L113-L115

```
        // Past expiration, hardcode the PT oracle price to 1. It is no longer tradable and
        // is worth 1 unit of the underlying SY at expiration.
        int256 ptRate = expiry <= block.timestamp ? ptDecimals : _getPTRate();
```

**Comment by WangSecurity** [comment]
Based on the comment above, I believe the oracle is sufficiently checked and I believe the issue is itself low severity. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [novaman33](https://github.com/sherlock-audit/2024-06-leveraged-vaults-judging/issues/7/#issuecomment-2222872429): accepted
